<?php if (!defined('ABSPATH')) {
  die;
} // Cannot access directly.
$prefix = 'mcs-opt';

$timezones = array(
  'Africa/Abidjan' => esc_html__('Africa/Abidjan', 'better-chat-support'),
  'Africa/Accra' => esc_html__('Africa/Accra', 'better-chat-support'),
  'Africa/Addis_Ababa' => esc_html__('Africa/Addis_Ababa', 'better-chat-support'),
  'Africa/Algiers' => esc_html__('Africa/Algiers', 'better-chat-support'),
  'Africa/Asmara' => esc_html__('Africa/Asmara', 'better-chat-support'),
  'Africa/Asmera' => esc_html__('Africa/Asmera', 'better-chat-support'),
  'Africa/Bamako' => esc_html__('Africa/Bamako', 'better-chat-support'),
  'Africa/Bangui' => esc_html__('Africa/Bangui', 'better-chat-support'),
  'Africa/Banjul' => esc_html__('Africa/Banjul', 'better-chat-support'),
  'Africa/Bissau' => esc_html__('Africa/Bissau', 'better-chat-support'),
  'Africa/Blantyre' => esc_html__('Africa/Blantyre', 'better-chat-support'),
  'Africa/Brazzaville' => esc_html__('Africa/Brazzaville', 'better-chat-support'),
  'Africa/Bujumbura' => esc_html__('Africa/Bujumbura', 'better-chat-support'),
  'Africa/Cairo' => esc_html__('Africa/Cairo', 'better-chat-support'),
  'Africa/Casablanca' => esc_html__('Africa/Casablanca', 'better-chat-support'),
  'Africa/Ceuta' => esc_html__('Africa/Ceuta', 'better-chat-support'),
  'Africa/Conakry' => esc_html__('Africa/Conakry', 'better-chat-support'),
  'Africa/Dakar' => esc_html__('Africa/Dakar', 'better-chat-support'),
  'Africa/Dar_es_Salaam' => esc_html__('Africa/Dar_es_Salaam', 'better-chat-support'),
  'Africa/Djibouti' => esc_html__('Africa/Djibouti', 'better-chat-support'),
  'Africa/Douala' => esc_html__('Africa/Douala', 'better-chat-support'),
  'Africa/El_Aaiun' => esc_html__('Africa/El_Aaiun', 'better-chat-support'),
  'Africa/Freetown' => esc_html__('Africa/Freetown', 'better-chat-support'),
  'Africa/Gaborone' => esc_html__('Africa/Gaborone', 'better-chat-support'),
  'Africa/Harare' => esc_html__('Africa/Harare', 'better-chat-support'),
  'Africa/Johannesburg' => esc_html__('Africa/Johannesburg', 'better-chat-support'),
  'Africa/Juba' => esc_html__('Africa/Juba', 'better-chat-support'),
  'Africa/Kampala' => esc_html__('Africa/Kampala', 'better-chat-support'),
  'Africa/Khartoum' => esc_html__('Africa/Khartoum', 'better-chat-support'),
  'Africa/Kigali' => esc_html__('Africa/Kigali', 'better-chat-support'),
  'Africa/Kinshasa' => esc_html__('Africa/Kinshasa', 'better-chat-support'),
  'Africa/Lagos' => esc_html__('Africa/Lagos', 'better-chat-support'),
  'Africa/Libreville' => esc_html__('Africa/Libreville', 'better-chat-support'),
  'Africa/Lome' => esc_html__('Africa/Lome', 'better-chat-support'),
  'Africa/Luanda' => esc_html__('Africa/Luanda', 'better-chat-support'),
  'Africa/Lubumbashi' => esc_html__('Africa/Lubumbashi', 'better-chat-support'),
  'Africa/Lusaka' => esc_html__('Africa/Lusaka', 'better-chat-support'),
  'Africa/Malabo' => esc_html__('Africa/Malabo', 'better-chat-support'),
  'Africa/Maputo' => esc_html__('Africa/Maputo', 'better-chat-support'),
  'Africa/Maseru' => esc_html__('Africa/Maseru', 'better-chat-support'),
  'Africa/Mbabane' => esc_html__('Africa/Mbabane', 'better-chat-support'),
  'Africa/Mogadishu' => esc_html__('Africa/Mogadishu', 'better-chat-support'),
  'Africa/Monrovia' => esc_html__('Africa/Monrovia', 'better-chat-support'),
  'Africa/Nairobi' => esc_html__('Africa/Nairobi', 'better-chat-support'),
  'Africa/Ndjamena' => esc_html__('Africa/Ndjamena', 'better-chat-support'),
  'Africa/Niamey' => esc_html__('Africa/Niamey', 'better-chat-support'),
  'Africa/Nouakchott' => esc_html__('Africa/Nouakchott', 'better-chat-support'),
  'Africa/Ouagadougou' => esc_html__('Africa/Ouagadougou', 'better-chat-support'),
  'Africa/Porto-Novo' => esc_html__('Africa/Porto-Novo', 'better-chat-support'),
  'Africa/Sao_Tome' => esc_html__('Africa/Sao_Tome', 'better-chat-support'),
  'Africa/Timbuktu' => esc_html__('Africa/Timbuktu', 'better-chat-support'),
  'Africa/Tripoli' => esc_html__('Africa/Tripoli', 'better-chat-support'),
  'Africa/Tunis' => esc_html__('Africa/Tunis', 'better-chat-support'),
  'Africa/Windhoek' => esc_html__('Africa/Windhoek', 'better-chat-support'),
  'America/Adak' => esc_html__('America/Adak', 'better-chat-support'),
  'America/Anchorage' => esc_html__('America/Anchorage', 'better-chat-support'),
  'America/Anguilla' => esc_html__('America/Anguilla', 'better-chat-support'),
  'America/Antigua' => esc_html__('America/Antigua', 'better-chat-support'),
  'America/Araguaina' => esc_html__('America/Araguaina', 'better-chat-support'),
  'America/Argentina/Buenos_Aires' => esc_html__('America/Argentina/Buenos_Aires', 'better-chat-support'),
  'America/Argentina/Catamarca' => esc_html__('America/Argentina/Catamarca', 'better-chat-support'),
  'America/Argentina/ComodRivadavia' => esc_html__('America/Argentina/ComodRivadavia', 'better-chat-support'),
  'America/Argentina/Cordoba' => esc_html__('America/Argentina/Cordoba', 'better-chat-support'),
  'America/Argentina/Jujuy' => esc_html__('America/Argentina/Jujuy', 'better-chat-support'),
  'America/Argentina/La_Rioja' => esc_html__('America/Argentina/La_Rioja', 'better-chat-support'),
  'America/Argentina/Mendoza' => esc_html__('America/Argentina/Mendoza', 'better-chat-support'),
  'America/Argentina/Rio_Gallegos' => esc_html__('America/Argentina/Rio_Gallegos', 'better-chat-support'),
  'America/Argentina/Salta' => esc_html__('America/Argentina/Salta', 'better-chat-support'),
  'America/Argentina/San_Juan' => esc_html__('America/Argentina/San_Juan', 'better-chat-support'),
  'America/Argentina/San_Luis' => esc_html__('America/Argentina/San_Luis', 'better-chat-support'),
  'America/Argentina/Tucuman' => esc_html__('America/Argentina/Tucuman', 'better-chat-support'),
  'America/Argentina/Ushuaia' => esc_html__('America/Argentina/Ushuaia', 'better-chat-support'),
  'America/Aruba' => esc_html__('America/Aruba', 'better-chat-support'),
  'America/Asuncion' => esc_html__('America/Asuncion', 'better-chat-support'),
  'America/Atikokan' => esc_html__('America/Atikokan', 'better-chat-support'),
  'America/Atka' => esc_html__('America/Atka', 'better-chat-support'),
  'America/Bahia' => esc_html__('America/Bahia', 'better-chat-support'),
  'America/Bahia_Banderas' => esc_html__('America/Bahia_Banderas', 'better-chat-support'),
  'America/Barbados' => esc_html__('America/Barbados', 'better-chat-support'),
  'America/Belem' => esc_html__('America/Belem', 'better-chat-support'),
  'America/Belize' => esc_html__('America/Belize', 'better-chat-support'),
  'America/Blanc-Sablon' => esc_html__('America/Blanc-Sablon', 'better-chat-support'),
  'America/Boa_Vista' => esc_html__('America/Boa_Vista', 'better-chat-support'),
  'America/Bogota' => esc_html__('America/Bogota', 'better-chat-support'),
  'America/Boise' => esc_html__('America/Boise', 'better-chat-support'),
  'America/Buenos_Aires' => esc_html__('America/Buenos_Aires', 'better-chat-support'),
  'America/Cambridge_Bay' => esc_html__('America/Cambridge_Bay', 'better-chat-support'),
  'America/Campo_Grande' => esc_html__('America/Campo_Grande', 'better-chat-support'),
  'America/Cancun' => esc_html__('America/Cancun', 'better-chat-support'),
  'America/Caracas' => esc_html__('America/Caracas', 'better-chat-support'),
  'America/Catamarca' => esc_html__('America/Catamarca', 'better-chat-support'),
  'America/Cayenne' => esc_html__('America/Cayenne', 'better-chat-support'),
  'America/Cayman' => esc_html__('America/Cayman', 'better-chat-support'),
  'America/Chicago' => esc_html__('America/Chicago', 'better-chat-support'),
  'America/Chihuahua' => esc_html__('America/Chihuahua', 'better-chat-support'),
  'America/Coral_Harbour' => esc_html__('America/Coral_Harbour', 'better-chat-support'),
  'America/Cordoba' => esc_html__('America/Cordoba', 'better-chat-support'),
  'America/Costa_Rica' => esc_html__('America/Costa_Rica', 'better-chat-support'),
  'America/Creston' => esc_html__('America/Creston', 'better-chat-support'),
  'America/Cuiaba' => esc_html__('America/Cuiaba', 'better-chat-support'),
  'America/Curacao' => esc_html__('America/Curacao', 'better-chat-support'),
  'America/Danmarkshavn' => esc_html__('America/Danmarkshavn', 'better-chat-support'),
  'America/Dawson' => esc_html__('America/Dawson', 'better-chat-support'),
  'America/Araguaina' => esc_html__('America/Araguaina', 'better-chat-support'),
  'America/Denver' => esc_html__('America/Denver', 'better-chat-support'),
  'America/Araguaina' => esc_html__('America/Araguaina', 'better-chat-support'),
  'America/Dominica' => esc_html__('America/Dominica', 'better-chat-support'),
  'America/Edmonton' => esc_html__('America/Edmonton', 'better-chat-support'),
  'America/Eirunepe' => esc_html__('America/Eirunepe', 'better-chat-support'),
  'America/El_Salvador' => esc_html__('America/El_Salvador', 'better-chat-support'),
  'America/Ensenada' => esc_html__('America/Ensenada', 'better-chat-support'),
  'America/Fort_Nelson' => esc_html__('America/Fort_Nelson', 'better-chat-support'),
  'America/Fort_Wayne' => esc_html__('America/Fort_Wayne', 'better-chat-support'),
  'America/Fortaleza' => esc_html__('America/Fortaleza', 'better-chat-support'),
  'America/Glace_Bay' => esc_html__('America/Glace_Bay', 'better-chat-support'),
  'America/Godthab' => esc_html__('America/Godthab', 'better-chat-support'),
  'America/Goose_Bay' => esc_html__('America/Goose_Bay', 'better-chat-support'),
  'America/Grand_Turk' => esc_html__('America/Grand_Turk', 'better-chat-support'),
  'America/Grenada' => esc_html__('America/Grenada', 'better-chat-support'),
  'America/Guadeloupe' => esc_html__('America/Guadeloupe', 'better-chat-support'),
  'America/Guatemala' => esc_html__('America/Guatemala', 'better-chat-support'),
  'America/Guayaquil' => esc_html__('America/Guayaquil', 'better-chat-support'),
  'America/Guyana' => esc_html__('America/Guyana', 'better-chat-support'),
  'America/Halifax' => esc_html__('America/Halifax', 'better-chat-support'),
  'America/Havana' => esc_html__('America/Havana', 'better-chat-support'),
  'America/Hermosillo' => esc_html__('America/Hermosillo', 'better-chat-support'),
  'America/Indiana/Indianapolis' => esc_html__('Indiana/Indianapolis', 'better-chat-support'),
  'America/Indiana/Knox' => esc_html__('America/Indiana/Knox', 'better-chat-support'),
  'America/Indiana/Marengo' => esc_html__('America/Indiana/Marengo', 'better-chat-support'),
  'America/Indiana/Petersburg' => esc_html__('America/Indiana/Petersburg', 'better-chat-support'),
  'America/Indiana/Tell_City' => esc_html__('America/Indiana/Tell_City', 'better-chat-support'),
  'America/Indiana/Vevay' => esc_html__('America/Indiana/Vevay', 'better-chat-support'),
  'America/Indiana/Vincennes' => esc_html__('America/Indiana/Vincennes', 'better-chat-support'),
  'America/Indiana/Winamac' => esc_html__('America/Indiana/Winamac', 'better-chat-support'),
  'America/Indianapolis' => esc_html__('America/Indianapolis', 'better-chat-support'),
  'America/Inuvik' => esc_html__('America/Inuvik', 'better-chat-support'),
  'America/Iqaluit' => esc_html__('America/Iqaluit', 'better-chat-support'),
  'America/Jamaica' => esc_html__('America/Jamaica', 'better-chat-support'),
  'America/Jujuy' => esc_html__('America/Jujuy', 'better-chat-support'),
  'America/Juneau' => esc_html__('America/Juneau', 'better-chat-support'),
  'America/Kentucky/Louisville' => esc_html__('America/Kentucky/Louisville', 'better-chat-support'),
  'America/Kentucky/Monticello' => esc_html__('America/Kentucky/Monticello', 'better-chat-support'),
  'America/Knox_IN' => esc_html__('America/Knox_IN', 'better-chat-support'),
  'America/Kralendijk' => esc_html__('America/Kralendijk', 'better-chat-support'),
  'America/La_Paz' => esc_html__('America/La_Paz', 'better-chat-support'),
  'America/Lima' => esc_html__('America/Lima', 'better-chat-support'),
  'America/Los_Angeles' => esc_html__('America/Los_Angeles', 'better-chat-support'),
  'America/Louisville' => esc_html__('America/Louisville', 'better-chat-support'),
  'America/Lower_Princes' => esc_html__('America/Lower_Princes', 'better-chat-support'),
  'America/Maceio' => esc_html__('America/Maceio', 'better-chat-support'),
  'America/Managua' => esc_html__('America/Managua', 'better-chat-support'),
  'America/Manaus' => esc_html__('America/Manaus', 'better-chat-support'),
  'America/Marigot' => esc_html__('America/Marigot', 'better-chat-support'),
  'America/Martinique' => esc_html__('America/Martinique', 'better-chat-support'),
  'America/Matamoros' => esc_html__('America/Matamoros', 'better-chat-support'),
  'America/Mazatlan' => esc_html__('America/Mazatlan', 'better-chat-support'),
  'America/Mendoza' => esc_html__('America/Mendoza', 'better-chat-support'),
  'America/Menominee' => esc_html__('America/Menominee', 'better-chat-support'),
  'America/Merida' => esc_html__('America/Merida', 'better-chat-support'),
  'America/Metlakatla' => esc_html__('America/Metlakatla', 'better-chat-support'),
  'America/Mexico_City' => esc_html__('America/Mexico_City', 'better-chat-support'),
  'America/Miquelon' => esc_html__('America/Miquelon', 'better-chat-support'),
  'America/Moncton' => esc_html__('America/Moncton', 'better-chat-support'),
  'America/Monterrey' => esc_html__('America/Monterrey', 'better-chat-support'),
  'America/Montevideo' => esc_html__('America/Montevideo', 'better-chat-support'),
  'America/Montreal' => esc_html__('America/Montreal', 'better-chat-support'),
  'America/Montserrat' => esc_html__('America/Montserrat', 'better-chat-support'),
  'America/Nassau' => esc_html__('America/Nassau', 'better-chat-support'),
  'America/New_York' => esc_html__('America/New_York', 'better-chat-support'),
  'America/Nipigon' => esc_html__('America/Nipigon', 'better-chat-support'),
  'America/Nome' => esc_html__('America/Nome', 'better-chat-support'),
  'America/Noronha' => esc_html__('America/Noronha', 'better-chat-support'),
  'America/North_Dakota/Beulah' => esc_html__('America/North_Dakota/Beulah', 'better-chat-support'),
  'America/North_Dakota/Center' => esc_html__('America/North_Dakota/Center', 'better-chat-support'),
  'America/North_Dakota/New_Salem' => esc_html__('America/North_Dakota/New_Salem', 'better-chat-support'),
  'America/Ojinaga' => esc_html__('America/Ojinaga', 'better-chat-support'),
  'America/Panama' => esc_html__('America/Panama', 'better-chat-support'),
  'America/Pangnirtung' => esc_html__('America/Pangnirtung', 'better-chat-support'),
  'America/Paramaribo' => esc_html__('America/Paramaribo', 'better-chat-support'),
  'America/Phoenix' => esc_html__('America/Phoenix', 'better-chat-support'),
  'America/Port-au-Prince' => esc_html__('America/Port-au-Prince', 'better-chat-support'),
  'America/Port_of_Spain' => esc_html__('America/Port_of_Spain', 'better-chat-support'),
  'America/Porto_Acre' => esc_html__('America/Porto_Acre', 'better-chat-support'),
  'America/Porto_Velho' => esc_html__('America/Porto_Velho', 'better-chat-support'),
  'America/Puerto_Rico' => esc_html__('America/Puerto_Rico', 'better-chat-support'),
  'America/Punta_Arenas' => esc_html__('America/Punta_Arenas', 'better-chat-support'),
  'America/Rainy_River' => esc_html__('America/Rainy_River', 'better-chat-support'),
  'America/Rankin_Inlet' => esc_html__('America/Rankin_Inlet', 'better-chat-support'),
  'America/Recife' => esc_html__('America/Recife', 'better-chat-support'),
  'America/Regina' => esc_html__('America/Regina', 'better-chat-support'),
  'America/Resolute' => esc_html__('America/Resolute', 'better-chat-support'),
  'America/Rio_Branco' => esc_html__('America/Rio_Branco', 'better-chat-support'),
  'America/Rosario' => esc_html__('America/Rosario', 'better-chat-support'),
  'America/Santa_Isabel' => esc_html__('America/Santa_Isabel', 'better-chat-support'),
  'America/Santarem' => esc_html__('America/Santarem', 'better-chat-support'),
  'America/Santiago' => esc_html__('America/Santiago', 'better-chat-support'),
  'America/Santo_Domingo' => esc_html__('America/Santo_Domingo', 'better-chat-support'),
  'America/Sao_Paulo' => esc_html__('America/Sao_Paulo', 'better-chat-support'),
  'America/Scoresbysund' => esc_html__('America/Scoresbysund', 'better-chat-support'),
  'America/Shiprock' => esc_html__('America/Shiprock', 'better-chat-support'),
  'America/Sitka' => esc_html__('America/Sitka', 'better-chat-support'),
  'America/St_Barthelemy' => esc_html__('America/St_Barthelemy', 'better-chat-support'),
  'America/St_Johns' => esc_html__('America/St_Johns', 'better-chat-support'),
  'America/St_Kitts' => esc_html__('America/St_Kitts', 'better-chat-support'),
  'America/St_Lucia' => esc_html__('America/St_Lucia', 'better-chat-support'),
  'America/St_Thomas' => esc_html__('America/St_Thomas', 'better-chat-support'),
  'America/St_Vincent' => esc_html__('America/St_Vincent', 'better-chat-support'),
  'America/Swift_Current' => esc_html__('America/Swift_Current', 'better-chat-support'),
  'America/Tegucigalpa' => esc_html__('America/Tegucigalpa', 'better-chat-support'),
  'America/Thule' => esc_html__('America/Thule', 'better-chat-support'),
  'America/Thunder_Bay' => esc_html__('America/Thunder_Bay', 'better-chat-support'),
  'America/Tijuana' => esc_html__('America/Tijuana', 'better-chat-support'),
  'America/Toronto' => esc_html__('America/Toronto', 'better-chat-support'),
  'America/Tortola' => esc_html__('America/Tortola', 'better-chat-support'),
  'America/Vancouver' => esc_html__('America/Vancouver', 'better-chat-support'),
  'America/Virgin' => esc_html__('America/Virgin', 'better-chat-support'),
  'America/Whitehorse' => esc_html__('America/Whitehorse', 'better-chat-support'),
  'America/Winnipeg' => esc_html__('America/Winnipeg', 'better-chat-support'),
  'America/Yakutat' => esc_html__('America/Yakutat', 'better-chat-support'),
  'America/Yellowknife' => esc_html__('America/Yellowknife', 'better-chat-support'),
  'Antarctica/Casey' => esc_html__('Antarctica/Casey', 'better-chat-support'),
  'Antarctica/Davis' => esc_html__('Antarctica/Davis', 'better-chat-support'),
  'Antarctica/DumontDUrville' => esc_html__('Antarctica/DumontDUrville', 'better-chat-support'),
  'Antarctica/Macquarie' => esc_html__('Antarctica/Macquarie', 'better-chat-support'),
  'Antarctica/Mawson' => esc_html__('Antarctica/Mawson', 'better-chat-support'),
  'Antarctica/McMurdo' => esc_html__('Antarctica/McMurdo', 'better-chat-support'),
  'Antarctica/Palmer' => esc_html__('Antarctica/Palmer', 'better-chat-support'),
  'Antarctica/Rothera' => esc_html__('Antarctica/Rothera', 'better-chat-support'),
  'Antarctica/South_Pole' => esc_html__('Antarctica/South_Pole', 'better-chat-support'),
  'Antarctica/Syowa' => esc_html__('Antarctica/Syowa', 'better-chat-support'),
  'Antarctica/Troll' => esc_html__('Antarctica/Troll', 'better-chat-support'),
  'Antarctica/Vostok' => esc_html__('Antarctica/Vostok', 'better-chat-support'),
  'Arctic/Longyearbyen' => esc_html__('Arctic/Longyearbyen', 'better-chat-support'),
  'Asia/Aden' => esc_html__('Asia/Aden', 'better-chat-support'),
  'Asia/Almaty' => esc_html__('Asia/Almaty', 'better-chat-support'),
  'Asia/Amman' => esc_html__('Asia/Amman', 'better-chat-support'),
  'Asia/Anadyr' => esc_html__('Asia/Anadyr', 'better-chat-support'),
  'Asia/Aqtau' => esc_html__('Asia/Aqtau', 'better-chat-support'),
  'Asia/Aqtobe' => esc_html__('Asia/Aqtobe', 'better-chat-support'),
  'Asia/Ashgabat' => esc_html__('Asia/Ashgabat', 'better-chat-support'),
  'Asia/Ashkhabad' => esc_html__('Asia/Ashkhabad', 'better-chat-support'),
  'Asia/Atyrau' => esc_html__('Asia/Atyrau', 'better-chat-support'),
  'Asia/Baghdad' => esc_html__('Asia/Baghdad', 'better-chat-support'),
  'Asia/Bahrain' => esc_html__('Asia/Bahrain', 'better-chat-support'),
  'Asia/Baku' => esc_html__('Asia/Baku', 'better-chat-support'),
  'Asia/Bangkok' => esc_html__('Asia/Bangkok', 'better-chat-support'),
  'Asia/Barnaul' => esc_html__('Asia/Barnaul', 'better-chat-support'),
  'Asia/Beirut' => esc_html__('Asia/Beirut', 'better-chat-support'),
  'Asia/Bishkek' => esc_html__('Asia/Bishkek', 'better-chat-support'),
  'Asia/Brunei' => esc_html__('Asia/Brunei', 'better-chat-support'),
  'Asia/Calcutta' => esc_html__('Asia/Calcutta', 'better-chat-support'),
  'Asia/Chita' => esc_html__('Asia/Chita', 'better-chat-support'),
  'Asia/Choibalsan' => esc_html__('Asia/Choibalsan', 'better-chat-support'),
  'Asia/Chongqing' => esc_html__('Asia/Chongqing', 'better-chat-support'),
  'Asia/Chungking' => esc_html__('Asia/Chungking', 'better-chat-support'),
  'Asia/Colombo' => esc_html__('Asia/Colombo', 'better-chat-support'),
  'Asia/Dacca' => esc_html__('Asia/Dacca', 'better-chat-support'),
  'Asia/Damascus' => esc_html__('Asia/Damascus', 'better-chat-support'),
  'Asia/Dhaka' => esc_html__('Asia/Dhaka', 'better-chat-support'),
  'Asia/Dili' => esc_html__('Asia/Dili', 'better-chat-support'),
  'Asia/Dubai' => esc_html__('Asia/Dubai', 'better-chat-support'),
  'Asia/Dushanbe' => esc_html__('Asia/Dushanbe', 'better-chat-support'),
  'Asia/Famagusta' => esc_html__('Asia/Famagusta', 'better-chat-support'),
  'Asia/Gaza' => esc_html__('Asia/Gaza', 'better-chat-support'),
  'Asia/Harbin' => esc_html__('Asia/Harbin', 'better-chat-support'),
  'Asia/Hebron' => esc_html__('Asia/Hebron', 'better-chat-support'),
  'Asia/Ho_Chi_Minh' => esc_html__('Asia/Ho_Chi_Minh', 'better-chat-support'),
  'Asia/Hong_Kong' => esc_html__('Asia/Hong_Kong', 'better-chat-support'),
  'Asia/Hovd' => esc_html__('Asia/Hovd', 'better-chat-support'),
  'Asia/Irkutsk' => esc_html__('Asia/Irkutsk', 'better-chat-support'),
  'Asia/Istanbul' => esc_html__('Asia/Istanbul', 'better-chat-support'),
  'Asia/Jakarta' => esc_html__('Asia/Jakarta', 'better-chat-support'),
  'Asia/Jayapura' => esc_html__('Asia/Jayapura', 'better-chat-support'),
  'Asia/Jerusalem' => esc_html__('Asia/Jerusalem', 'better-chat-support'),
  'Asia/Kabul' => esc_html__('Asia/Kabul', 'better-chat-support'),
  'Asia/Kamchatka' => esc_html__('Asia/Kamchatka', 'better-chat-support'),
  'Asia/Karachi' => esc_html__('Asia/Karachi', 'better-chat-support'),
  'Asia/Kashgar' => esc_html__('Asia/Kashgar', 'better-chat-support'),
  'Asia/Kathmandu' => esc_html__('Asia/Kathmandu', 'better-chat-support'),
  'Asia/Katmandu' => esc_html__('Asia/Katmandu', 'better-chat-support'),
  'Asia/Khandyga' => esc_html__('Asia/Khandyga', 'better-chat-support'),
  'Asia/Kolkata' => esc_html__('Asia/Kolkata', 'better-chat-support'),
  'Asia/Krasnoyarsk' => esc_html__('Asia/Krasnoyarsk', 'better-chat-support'),
  'Asia/Kuala_Lumpur' => esc_html__('Asia/Kuala_Lumpur', 'better-chat-support'),
  'Asia/Kuching' => esc_html__('Asia/Kuching', 'better-chat-support'),
  'Asia/Kuwait' => esc_html__('Asia/Kuwait', 'better-chat-support'),
  'Asia/Macao' => esc_html__('Asia/Macao', 'better-chat-support'),
  'Asia/Macau' => esc_html__('Asia/Macau', 'better-chat-support'),
  'Asia/Magadan' => esc_html__('Asia/Magadan', 'better-chat-support'),
  'Asia/Makassar' => esc_html__('Asia/Makassar', 'better-chat-support'),
  'Asia/Manila' => esc_html__('Asia/Manila', 'better-chat-support'),
  'Asia/Muscat' => esc_html__('Asia/Muscat', 'better-chat-support'),
  'Asia/Nicosia' => esc_html__('Asia/Nicosia', 'better-chat-support'),
  'Asia/Novokuznetsk' => esc_html__('Asia/Novokuznetsk', 'better-chat-support'),
  'Asia/Novosibirsk' => esc_html__('Asia/Novosibirsk', 'better-chat-support'),
  'Asia/Omsk' => esc_html__('Asia/Omsk', 'better-chat-support'),
  'Asia/Oral' => esc_html__('Asia/Oral', 'better-chat-support'),
  'Asia/Phnom_Penh' => esc_html__('Asia/Phnom_Penh', 'better-chat-support'),
  'Asia/Pontianak' => esc_html__('Asia/Pontianak', 'better-chat-support'),
  'Asia/Pyongyang' => esc_html__('Asia/Pyongyang', 'better-chat-support'),
  'Asia/Qatar' => esc_html__('Asia/Qatar', 'better-chat-support'),
  'Asia/Qyzylorda' => esc_html__('Asia/Qyzylorda', 'better-chat-support'),
  'Asia/Rangoon' => esc_html__('Asia/Rangoon', 'better-chat-support'),
  'Asia/Riyadh' => esc_html__('Asia/Riyadh', 'better-chat-support'),
  'Asia/Saigon' => esc_html__('Asia/Saigon', 'better-chat-support'),
  'Asia/Sakhalin' => esc_html__('Asia/Sakhalin', 'better-chat-support'),
  'Asia/Samarkand' => esc_html__('Asia/Samarkand', 'better-chat-support'),
  'Asia/Seoul' => esc_html__('Asia/Seoul', 'better-chat-support'),
  'Asia/Shanghai' => esc_html__('Asia/Shanghai', 'better-chat-support'),
  'Asia/Singapore' => esc_html__('Asia/Singapore', 'better-chat-support'),
  'Asia/Srednekolymsk' => esc_html__('Asia/Srednekolymsk', 'better-chat-support'),
  'Asia/Taipei' => esc_html__('Asia/Taipei', 'better-chat-support'),
  'Asia/Tashkent' => esc_html__('Asia/Tashkent', 'better-chat-support'),
  'Asia/Tbilisi' => esc_html__('Asia/Tbilisi', 'better-chat-support'),
  'Asia/Tehran' => esc_html__('Asia/Tehran', 'better-chat-support'),
  'Asia/Tel_Aviv' => esc_html__('Asia/Tel_Aviv', 'better-chat-support'),
  'Asia/Thimbu' => esc_html__('Asia/Thimbu', 'better-chat-support'),
  'Asia/Thimphu' => esc_html__('Asia/Thimphu', 'better-chat-support'),
  'Asia/Tokyo' => esc_html__('Asia/Tokyo', 'better-chat-support'),
  'Asia/Tomsk' => esc_html__('Asia/Tomsk', 'better-chat-support'),
  'Asia/Ujung_Pandang' => esc_html__('Asia/Ujung_Pandang', 'better-chat-support'),
  'Asia/Ulaanbaatar' => esc_html__('Asia/Ulaanbaatar', 'better-chat-support'),
  'Asia/Ulan_Bator' => esc_html__('Asia/Ulan_Bator', 'better-chat-support'),
  'Asia/Urumqi' => esc_html__('Asia/Urumqi', 'better-chat-support'),
  'Asia/Ust-Nera' => esc_html__('Asia/Ust-Nera', 'better-chat-support'),
  'Asia/Vientiane' => esc_html__('Asia/Vientiane', 'better-chat-support'),
  'Asia/Vladivostok' => esc_html__('Asia/Vladivostok', 'better-chat-support'),
  'Asia/Yakutsk' => esc_html__('Asia/Yakutsk', 'better-chat-support'),
  'Asia/Yangon' => esc_html__('Asia/Yangon', 'better-chat-support'),
  'Asia/Yekaterinburg' => esc_html__('Asia/Yekaterinburg', 'better-chat-support'),
  'Asia/Yerevan' => esc_html__('Asia/Yerevan', 'better-chat-support'),
  'Atlantic/Azores' => esc_html__('Atlantic/Azores', 'better-chat-support'),
  'Atlantic/Bermuda' => esc_html__('Atlantic/Bermuda', 'better-chat-support'),
  'Atlantic/Canary' => esc_html__('Atlantic/Canary', 'better-chat-support'),
  'Atlantic/Cape_Verde' => esc_html__('Atlantic/Cape_Verde', 'better-chat-support'),
  'Atlantic/Faeroe' => esc_html__('Atlantic/Faeroe', 'better-chat-support'),
  'Atlantic/Faroe' => esc_html__('Atlantic/Faroe', 'better-chat-support'),
  'Atlantic/Jan_Mayen' => esc_html__('Atlantic/Jan_Mayen', 'better-chat-support'),
  'Atlantic/Madeira' => esc_html__('Atlantic/Madeira', 'better-chat-support'),
  'Atlantic/Reykjavik' => esc_html__('Atlantic/Reykjavik', 'better-chat-support'),
  'Atlantic/South_Georgia' => esc_html__('Atlantic/South_Georgia', 'better-chat-support'),
  'Atlantic/St_Helena' => esc_html__('Atlantic/St_Helena', 'better-chat-support'),
  'Atlantic/Stanley' => esc_html__('Atlantic/Stanley', 'better-chat-support'),
  'Australia/ACT' => esc_html__('Australia/ACT', 'better-chat-support'),
  'Australia/Adelaide' => esc_html__('Australia/Adelaide', 'better-chat-support'),
  'Australia/Brisbane' => esc_html__('Australia/Brisbane', 'better-chat-support'),
  'Australia/Broken_Hill' => esc_html__('Asia/Broken_Hill', 'better-chat-support'),
  'Australia/Canberra' => esc_html__('Australia/Canberra', 'better-chat-support'),
  'Australia/Currie' => esc_html__('Australia/Currie', 'better-chat-support'),
  'Australia/Darwin' => esc_html__('Australia/Darwin', 'better-chat-support'),
  'Australia/Eucla' => esc_html__('Australia/Eucla', 'better-chat-support'),
  'Australia/Hobart' => esc_html__('Australia/Hobart', 'better-chat-support'),
  'Australia/LHI' => esc_html__('Australia/LHI', 'better-chat-support'),
  'Australia/Lindeman' => esc_html__('Australia/Lindeman', 'better-chat-support'),
  'Australia/Lord_Howe' => esc_html__('Australia/Lord_Howe', 'better-chat-support'),
  'Australia/Melbourne' => esc_html__('Australia/Melbourne', 'better-chat-support'),
  'Australia/NSW' => esc_html__('Australia/NSW', 'better-chat-support'),
  'Australia/North' => esc_html__('Australia/North', 'better-chat-support'),
  'Australia/Perth' => esc_html__('Australia/Perth', 'better-chat-support'),
  'Australia/Queensland' => esc_html__('Australia/Queensland', 'better-chat-support'),
  'Australia/South' => esc_html__('Australia/South', 'better-chat-support'),
  'Australia/Sydney' => esc_html__('Australia/Sydney', 'better-chat-support'),
  'Australia/Tasmania' => esc_html__('Australia/Tasmania', 'better-chat-support'),
  'Australia/Victoria' => esc_html__('Australia/Victoria', 'better-chat-support'),
  'Australia/West' => esc_html__('Australia/West', 'better-chat-support'),
  'Australia/Yancowinna' => esc_html__('Australia/Yancowinna', 'better-chat-support'),
  'Brazil/Acre' => esc_html__('Brazil/Acre', 'better-chat-support'),
  'Brazil/DeNoronha' => esc_html__('Brazil/DeNoronha', 'better-chat-support'),
  'Brazil/East' => esc_html__('Brazil/East', 'better-chat-support'),
  'Brazil/West' => esc_html__('Brazil/West', 'better-chat-support'),
  'CET' => esc_html__('CET', 'better-chat-support'),
  'CST6CDT' => esc_html__('CST6CDT', 'better-chat-support'),
  'Canada/Atlantic' => esc_html__('Canada/Atlantic', 'better-chat-support'),
  'Canada/Central' => esc_html__('Canada/Central', 'better-chat-support'),
  'Canada/Eastern' => esc_html__('Canada/Eastern', 'better-chat-support'),
  'Canada/Mountain' => esc_html__('Canada/Mountain', 'better-chat-support'),
  'Canada/Newfoundland' => esc_html__('Canada/Newfoundland', 'better-chat-support'),
  'Canada/Pacific' => esc_html__('Canada/Pacific', 'better-chat-support'),
  'Canada/Saskatchewan' => esc_html__('Canada/Saskatchewan', 'better-chat-support'),
  'Canada/Yukon' => esc_html__('Canada/Yukon', 'better-chat-support'),
  'Chile/Continental' => esc_html__('Chile/Continental', 'better-chat-support'),
  'Chile/EasterIsland' => esc_html__('Chile/EasterIsland', 'better-chat-support'),
  'Cuba' => esc_html__('Cuba', 'better-chat-support'),
  'EET' => esc_html__('EET', 'better-chat-support'),
  'EST' => esc_html__('EST', 'better-chat-support'),
  'EST5EDT' => esc_html__('EST5EDT', 'better-chat-support'),
  'Egypt' => esc_html__('Egypt', 'better-chat-support'),
  'Eire' => esc_html__('Eire', 'better-chat-support'),
  'Etc/GMT' => esc_html__('Etc/GMT', 'better-chat-support'),
  'Etc/GMT+0' => esc_html__('Etc/GMT+0', 'better-chat-support'),
  'Etc/GMT+1' => esc_html__('Etc/GMT+1', 'better-chat-support'),
  'Etc/GMT+10' => esc_html__('Etc/GMT+10', 'better-chat-support'),
  'Etc/GMT+11' => esc_html__('Etc/GMT+11', 'better-chat-support'),
  'Etc/GMT+12' => esc_html__('Etc/GMT+12', 'better-chat-support'),
  'Etc/GMT+2' => esc_html__('Etc/GMT+2', 'better-chat-support'),
  'Etc/GMT+3' => esc_html__('Etc/GMT+3', 'better-chat-support'),
  'Etc/GMT+4' => esc_html__('Etc/GMT+4', 'better-chat-support'),
  'Etc/GMT+5' => esc_html__('Etc/GMT+5', 'better-chat-support'),
  'Etc/GMT+6' => esc_html__('Etc/GMT+6', 'better-chat-support'),
  'Etc/GMT+7' => esc_html__('Etc/GMT+7', 'better-chat-support'),
  'Etc/GMT+8' => esc_html__('Etc/GMT+8', 'better-chat-support'),
  'Etc/GMT+9' => esc_html__('Etc/GMT+9', 'better-chat-support'),
  'Etc/GMT-0' => esc_html__('Etc/GMT-0', 'better-chat-support'),
  'Etc/GMT-1' => esc_html__('Etc/GMT-1', 'better-chat-support'),
  'Etc/GMT-10' => esc_html__('Etc/GMT-10', 'better-chat-support'),
  'Etc/GMT-11' => esc_html__('Etc/GMT-11', 'better-chat-support'),
  'Etc/GMT-12' => esc_html__('Etc/GMT-12', 'better-chat-support'),
  'Etc/GMT-13' => esc_html__('Etc/GMT-13', 'better-chat-support'),
  'Etc/GMT-14' => esc_html__('Etc/GMT-14', 'better-chat-support'),
  'Etc/GMT-2' => esc_html__('Etc/GMT-2', 'better-chat-support'),
  'Etc/GMT-3' => esc_html__('Etc/GMT-3', 'better-chat-support'),
  'Etc/GMT-4' => esc_html__('Etc/GMT-4', 'better-chat-support'),
  'Etc/GMT-5' => esc_html__('Etc/GMT-5', 'better-chat-support'),
  'Etc/GMT-6' => esc_html__('Etc/GMT-6', 'better-chat-support'),
  'Etc/GMT-7' => esc_html__('Etc/GMT-7', 'better-chat-support'),
  'Etc/GMT-8' => esc_html__('Etc/GMT-8', 'better-chat-support'),
  'Etc/GMT-9' => esc_html__('Etc/GMT-9', 'better-chat-support'),
  'Etc/GMT0' => esc_html__('Etc/GMT0', 'better-chat-support'),
  'Etc/Greenwich' => esc_html__('Etc/Greenwich', 'better-chat-support'),
  'Etc/UCT' => esc_html__('Etc/UCT', 'better-chat-support'),
  'Etc/UTC' => esc_html__('Etc/UTC', 'better-chat-support'),
  'Etc/Universal' => esc_html__('Etc/Universal', 'better-chat-support'),
  'Etc/Zulu' => esc_html__('Etc/Zulu', 'better-chat-support'),
  'Europe/Amsterdam' => esc_html__('Europe/Amsterdam', 'better-chat-support'),
  'Europe/Andorra' => esc_html__('Europe/Andorra', 'better-chat-support'),
  'Europe/Astrakhan' => esc_html__('Europe/Astrakhan', 'better-chat-support'),
  'Europe/Athens' => esc_html__('Europe/Athens', 'better-chat-support'),
  'Europe/Belfast' => esc_html__('Europe/Belfast', 'better-chat-support'),
  'Europe/Belgrade' => esc_html__('Europe/Belgrade', 'better-chat-support'),
  'Europe/Berlin' => esc_html__('Europe/Berlin', 'better-chat-support'),
  'Europe/Bratislava' => esc_html__('Europe/Bratislava', 'better-chat-support'),
  'Europe/Brussels' => esc_html__('Europe/Brussels', 'better-chat-support'),
  'Europe/Bucharest' => esc_html__('Europe/Bucharest', 'better-chat-support'),
  'Europe/Budapest' => esc_html__('Europe/Budapest', 'better-chat-support'),
  'Europe/Busingen' => esc_html__('Europe/Busingen', 'better-chat-support'),
  'Europe/Chisinau' => esc_html__('Europe/Chisinau', 'better-chat-support'),
  'Europe/Copenhagen' => esc_html__('Europe/Copenhagen', 'better-chat-support'),
  'Europe/Dublin' => esc_html__('Europe/Dublin', 'better-chat-support'),
  'Europe/Gibraltar' => esc_html__('Europe/Gibraltar', 'better-chat-support'),
  'Europe/Guernsey' => esc_html__('Europe/Guernsey', 'better-chat-support'),
  'Europe/Helsinki' => esc_html__('Europe/Helsinki', 'better-chat-support'),
  'Europe/Isle_of_Man' => esc_html__('Europe/Isle_of_Man', 'better-chat-support'),
  'Europe/Istanbul' => esc_html__('Europe/Istanbul', 'better-chat-support'),
  'Europe/Jersey' => esc_html__('Europe/Jersey', 'better-chat-support'),
  'Europe/Kaliningrad' => esc_html__('Europe/Kaliningrad', 'better-chat-support'),
  'Europe/Kiev' => esc_html__('Europe/Kiev', 'better-chat-support'),
  'Europe/Kirov' => esc_html__('Europe/Kirov', 'better-chat-support'),
  'Europe/Lisbon' => esc_html__('Europe/Lisbon', 'better-chat-support'),
  'Europe/Ljubljana' => esc_html__('Europe/Ljubljana', 'better-chat-support'),
  'Europe/London' => esc_html__('Europe/London', 'better-chat-support'),
  'Europe/Luxembourg' => esc_html__('Europe/Luxembourg', 'better-chat-support'),
  'Europe/Madrid' => esc_html__('Europe/Madrid', 'better-chat-support'),
  'Europe/Malta' => esc_html__('Europe/Malta', 'better-chat-support'),
  'Europe/Mariehamn' => esc_html__('Europe/Mariehamn', 'better-chat-support'),
  'Europe/Minsk' => esc_html__('Europe/Minsk', 'better-chat-support'),
  'Europe/Monaco' => esc_html__('Europe/Monaco', 'better-chat-support'),
  'Europe/Moscow' => esc_html__('Europe/Moscow', 'better-chat-support'),
  'Europe/Nicosia' => esc_html__('Europe/Nicosia', 'better-chat-support'),
  'Europe/Oslo' => esc_html__('Europe/Oslo', 'better-chat-support'),
  'Europe/Paris' => esc_html__('Europe/Paris', 'better-chat-support'),
  'Europe/Podgorica' => esc_html__('Europe/Podgorica', 'better-chat-support'),
  'Europe/Prague' => esc_html__('Europe/Prague', 'better-chat-support'),
  'Europe/Riga' => esc_html__('Europe/Riga', 'better-chat-support'),
  'Europe/Rome' => esc_html__('Europe/Rome', 'better-chat-support'),
  'Europe/Samara' => esc_html__('Europe/Samara', 'better-chat-support'),
  'Europe/San_Marino' => esc_html__('Europe/San_Marino', 'better-chat-support'),
  'Europe/Sarajevo' => esc_html__('Europe/Sarajevo', 'better-chat-support'),
  'Europe/Saratov' => esc_html__('Europe/Saratov', 'better-chat-support'),
  'Europe/Simferopol' => esc_html__('Europe/Simferopol', 'better-chat-support'),
  'Europe/Skopje' => esc_html__('Europe/Skopje', 'better-chat-support'),
  'Europe/Sofia' => esc_html__('Europe/Sofia', 'better-chat-support'),
  'Europe/Stockholm' => esc_html__('Europe/Stockholm', 'better-chat-support'),
  'Europe/Tallinn' => esc_html__('Europe/Tallinn', 'better-chat-support'),
  'Europe/Tirane' => esc_html__('Europe/Tirane', 'better-chat-support'),
  'Europe/Tiraspol' => esc_html__('Europe/Tiraspol', 'better-chat-support'),
  'Europe/Ulyanovsk' => esc_html__('Europe/Ulyanovsk', 'better-chat-support'),
  'Europe/Uzhgorod' => esc_html__('Europe/Uzhgorod', 'better-chat-support'),
  'Europe/Vaduz' => esc_html__('Europe/Vaduz', 'better-chat-support'),
  'Europe/Vatican' => esc_html__('Europe/Vatican', 'better-chat-support'),
  'Europe/Vienna' => esc_html__('Europe/Vienna', 'better-chat-support'),
  'Europe/Vilnius' => esc_html__('Europe/Vilnius', 'better-chat-support'),
  'Europe/Volgograd' => esc_html__('Europe/Volgograd', 'better-chat-support'),
  'Europe/Warsaw' => esc_html__('Europe/Warsaw', 'better-chat-support'),
  'Europe/Zagreb' => esc_html__('Europe/Zagreb', 'better-chat-support'),
  'Europe/Zaporozhye' => esc_html__('Europe/Zaporozhye', 'better-chat-support'),
  'Europe/Zurich' => esc_html__('Europe/Zurich', 'better-chat-support'),
  'GB' => esc_html__('GB', 'better-chat-support'),
  'GB-Eire' => esc_html__('GB-Eire', 'better-chat-support'),
  'GMT' => esc_html__('GMT', 'better-chat-support'),
  'GMT+0' => esc_html__('GMT+0', 'better-chat-support'),
  'GMT-0' => esc_html__('GMT-0', 'better-chat-support'),
  'GMT0' => esc_html__('GMT0', 'better-chat-support'),
  'Greenwich' => esc_html__('Greenwich', 'better-chat-support'),
  'HST' => esc_html__('HST', 'better-chat-support'),
  'Hongkong' => esc_html__('Hongkong', 'better-chat-support'),
  'Iceland' => esc_html__('Iceland', 'better-chat-support'),
  'Indian/Antananarivo' => esc_html__('Indian/Antananarivo', 'better-chat-support'),
  'Indian/Chagos' => esc_html__('Indian/Chagos', 'better-chat-support'),
  'Indian/Christmas' => esc_html__('Indian/Christmas', 'better-chat-support'),
  'Indian/Cocos' => esc_html__('Indian/Cocos', 'better-chat-support'),
  'Indian/Comoro' => esc_html__('Indian/Comoro', 'better-chat-support'),
  'Indian/Kerguelen' => esc_html__('Indian/Kerguelen', 'better-chat-support'),
  'Indian/Mahe' => esc_html__('Indian/Mahe', 'better-chat-support'),
  'Indian/Maldives' => esc_html__('Indian/Maldives', 'better-chat-support'),
  'Indian/Mauritius' => esc_html__('Indian/Mauritius', 'better-chat-support'),
  'Indian/Mayotte' => esc_html__('Indian/Mayotte', 'better-chat-support'),
  'Indian/Reunion' => esc_html__('Indian/Reunion', 'better-chat-support'),
  'Iran' => esc_html__('Iran', 'better-chat-support'),
  'Israel' => esc_html__('Israel', 'better-chat-support'),
  'Jamaica' => esc_html__('Jamaica', 'better-chat-support'),
  'Japan' => esc_html__('Japan', 'better-chat-support'),
  'Kwajalein' => esc_html__('Kwajalein', 'better-chat-support'),
  'Libya' => esc_html__('Libya', 'better-chat-support'),
  'MET' => esc_html__('MET', 'better-chat-support'),
  'MST' => esc_html__('MST', 'better-chat-support'),
  'MST7MDT' => esc_html__('MST7MDT', 'better-chat-support'),
  'Mexico/BajaNorte' => esc_html__('Mexico/BajaNorte', 'better-chat-support'),
  'Mexico/BajaSur' => esc_html__('Mexico/BajaSur', 'better-chat-support'),
  'Mexico/General' => esc_html__('Mexico/General', 'better-chat-support'),
  'NZ' => esc_html__('NZ', 'better-chat-support'),
  'NZ-CHAT' => esc_html__('NZ-CHAT', 'better-chat-support'),
  'Navajo' => esc_html__('Navajo', 'better-chat-support'),
  'PRC' => esc_html__('PRC', 'better-chat-support'),
  'PST8PDT' => esc_html__('PST8PDT', 'better-chat-support'),
  'Pacific/Apia' => esc_html__('Pacific/Apia', 'better-chat-support'),
  'Pacific/Auckland' => esc_html__('Pacific/Auckland', 'better-chat-support'),
  'Pacific/Bougainville' => esc_html__('Pacific/Bougainville', 'better-chat-support'),
  'Pacific/Chatham' => esc_html__('Pacific/Chatham', 'better-chat-support'),
  'Pacific/Chuuk' => esc_html__('Pacific/Chuuk', 'better-chat-support'),
  'Pacific/Easter' => esc_html__('Pacific/Easter', 'better-chat-support'),
  'Pacific/Efate' => esc_html__('Pacific/Efate', 'better-chat-support'),
  'Pacific/Enderbury' => esc_html__('Pacific/Enderbury', 'better-chat-support'),
  'Pacific/Fakaofo' => esc_html__('Pacific/Fakaofo', 'better-chat-support'),
  'Pacific/Fiji' => esc_html__('Pacific/Fiji', 'better-chat-support'),
  'Pacific/Funafuti' => esc_html__('Pacific/Funafuti', 'better-chat-support'),
  'Pacific/Galapagos' => esc_html__('Pacific/Galapagos', 'better-chat-support'),
  'Pacific/Gambier' => esc_html__('Pacific/Gambier', 'better-chat-support'),
  'Pacific/Guadalcanal' => esc_html__('Pacific/Guadalcanal', 'better-chat-support'),
  'Pacific/Guam' => esc_html__('Pacific/Guam', 'better-chat-support'),
  'Pacific/Honolulu' => esc_html__('Pacific/Honolulu', 'better-chat-support'),
  'Pacific/Johnston' => esc_html__('Pacific/Johnston', 'better-chat-support'),
  'Pacific/Kiritimati' => esc_html__('Pacific/Kiritimati', 'better-chat-support'),
  'Pacific/Kosrae' => esc_html__('Pacific/Kosrae', 'better-chat-support'),
  'Pacific/Kwajalein' => esc_html__('Pacific/Kwajalein', 'better-chat-support'),
  'Pacific/Majuro' => esc_html__('Pacific/Majuro', 'better-chat-support'),
  'Pacific/Marquesas' => esc_html__('Pacific/Marquesas', 'better-chat-support'),
  'Pacific/Midway' => esc_html__('Pacific/Midway', 'better-chat-support'),
  'Pacific/Nauru' => esc_html__('Pacific/Nauru', 'better-chat-support'),
  'Pacific/Niue' => esc_html__('Pacific/Niue', 'better-chat-support'),
  'Pacific/Norfolk' => esc_html__('Pacific/Norfolk', 'better-chat-support'),
  'Pacific/Noumea' => esc_html__('Pacific/Noumea', 'better-chat-support'),
  'Pacific/Pago_Pago' => esc_html__('Pacific/Pago_Pago', 'better-chat-support'),
  'Pacific/Palau' => esc_html__('Pacific/Palau', 'better-chat-support'),
  'Pacific/Pitcairn' => esc_html__('Pacific/Pitcairn', 'better-chat-support'),
  'Pacific/Pohnpei' => esc_html__('Pacific/Pohnpei', 'better-chat-support'),
  'Pacific/Ponape' => esc_html__('Pacific/Ponape', 'better-chat-support'),
  'Pacific/Port_Moresby' => esc_html__('Pacific/Port_Moresby', 'better-chat-support'),
  'Pacific/Rarotonga' => esc_html__('Pacific/Rarotonga', 'better-chat-support'),
  'Pacific/Saipan' => esc_html__('Pacific/Saipan', 'better-chat-support'),
  'Pacific/Samoa' => esc_html__('Pacific/Samoa', 'better-chat-support'),
  'Pacific/Tahiti' => esc_html__('Pacific/Tahiti', 'better-chat-support'),
  'Pacific/Tarawa' => esc_html__('Pacific/Tarawa', 'better-chat-support'),
  'Pacific/Tongatapu' => esc_html__('Pacific/Tongatapu', 'better-chat-support'),
  'Pacific/Truk' => esc_html__('Pacific/Truk', 'better-chat-support'),
  'Pacific/Wake' => esc_html__('Pacific/Wake', 'better-chat-support'),
  'Pacific/Wallis' => esc_html__('Pacific/Wallis', 'better-chat-support'),
  'Pacific/Yap' => esc_html__('Pacific/Yap', 'better-chat-support'),
  'Poland' => esc_html__('Poland', 'better-chat-support'),
  'Portugal' => esc_html__('Portugal', 'better-chat-support'),
  'ROC' => esc_html__('ROC', 'better-chat-support'),
  'ROK' => esc_html__('ROK', 'better-chat-support'),
  'Singapore' => esc_html__('Singapore', 'better-chat-support'),
  'Turkey' => esc_html__('Turkey', 'better-chat-support'),
  'UCT' => esc_html__('UCT', 'better-chat-support'),
  'US/Alaska' => esc_html__('US/Alaska', 'better-chat-support'),
  'US/Aleutian' => esc_html__('US/Aleutian', 'better-chat-support'),
  'US/Arizona' => esc_html__('US/Arizona', 'better-chat-support'),
  'US/Central' => esc_html__('US/Central', 'better-chat-support'),
  'US/East-Indiana' => esc_html__('US/East-Indiana', 'better-chat-support'),
  'US/Eastern' => esc_html__('US/Eastern', 'better-chat-support'),
  'US/Hawaii' => esc_html__('US/Hawaii', 'better-chat-support'),
  'US/Indiana-Starke' => esc_html__('US/Indiana-Starke', 'better-chat-support'),
  'US/Michigan' => esc_html__('US/Michigan', 'better-chat-support'),
  'US/Mountain' => esc_html__('US/Mountain', 'better-chat-support'),
  'US/Pacific' => esc_html__('US/Pacific', 'better-chat-support'),
  'US/Pacific-New' => esc_html__('US/Pacific-New', 'better-chat-support'),
  'US/Samoa' => esc_html__('US/Samoa', 'better-chat-support'),
  'UTC' => esc_html__('UTC', 'better-chat-support'),
  'Universal' => esc_html__('Universal', 'better-chat-support'),
  'W-SU' => esc_html__('W-SU', 'better-chat-support'),
  'WET' => esc_html__('WET', 'better-chat-support'),
);
//
// Create options
//
CSF::createOptions($prefix, array(
  'menu_title'          => esc_html__('Messenger chat support', 'better-chat-support'),
  'menu_slug'           => 'mcs',
  'menu_icon'           => 'dashicons-format-chat',
  'framework_title'     => 'Messenger chat support <small>by ThemeAtelier</small>',
  'show_bar_menu'       => false,
  'footer_text'         => esc_html__('Thank you for using our product', 'better-chat-support'),
  'theme'               => 'light',
  'show_sub_menu'       => false,
  'show_bar_menu'       => false,
  'nav'                 => 'inline',
));


//
// Create a section
//
CSF::createSection($prefix, array(
  'title'  => esc_html__('GENERAL', 'better-chat-support'),
  'icon'   => 'fab fa-facebook-messenger',
  'fields' => array(



    // adding contact number
    array(
      'id'    => 'opt-fbid',
      'type'  => 'text',
      'title' => esc_html__('Facebook ID', 'better-chat-support'),
      'default'  => 'ThemeAtelier',
      'subtitle'  => esc_html__('Add your profile or page ID for recivingv messages. eg: ThemeAtelier', 'better-chat-support'),
    ),


    // changeing timezone
    array(
      'id'    => 'select-timezone',
      'type'  => 'select',
      'title' => esc_html__('Timezone', 'better-chat-support'),
      'subtitle' => esc_html__('When using the date and time from the user browser you can transform it to your current timezone (in case your user is in a different timezone)', 'better-chat-support'),
      'chosen'      => true,
      'placeholder' => esc_html__('Select timezone', 'better-chat-support'),

      'options' => $timezones,
    ),

    // Add availablity
    array(
      'id'    => 'opt-availablity',
      'type'  => 'tabbed',
      'title' => esc_html__('Availablity', 'better-chat-support'),
      'subtitle' => esc_html__('24-hour Time without PM:AM" eg: From 00:00 to 23:59. If you are offline for any specefic full day use 00:00 and 00:00 in From and To value.', 'better-chat-support'),
      // sunday
      'tabs'  => array(
        array(
          'title'  => esc_html__('Sunday', 'better-chat-support'),
          'fields' => array(
            array(
              'id'       => 'availablity-sunday',
              'type'     => 'datetime',
              'from_to'  => true,
              'settings' => array(
                'noCalendar' => true,
                'enableTime' => true,
                'dateFormat' => 'H:i',
                'time_24hr'  => true,
              ),
            ),
          ),
        ),
        // monday
        array(
          'title'  => esc_html__('Monday', 'better-chat-support'),
          'fields' => array(
            array(
              'id'       => 'availablity-monday',
              'type'     => 'datetime',
              'from_to'  => true,
              'settings' => array(
                'noCalendar' => true,
                'enableTime' => true,
                'dateFormat' => 'H:i',
                'time_24hr'  => true,
              ),
            ),
          ),
        ),
        // tuesday
        array(
          'title'  => esc_html__('Tuesday', 'better-chat-support'),
          'fields' => array(
            array(
              'id'       => 'availablity-tuesday',
              'type'     => 'datetime',
              'from_to'  => true,
              'settings' => array(
                'noCalendar' => true,
                'enableTime' => true,
                'dateFormat' => 'H:i',
                'time_24hr'  => true,
              ),
            ),
          ),
        ),
        // wednesday
        array(
          'title'  => esc_html__('Wednesday', 'better-chat-support'),
          'fields' => array(
            array(
              'id'       => 'availablity-wednesday',
              'type'     => 'datetime',
              'from_to'  => true,
              'settings' => array(
                'noCalendar' => true,
                'enableTime' => true,
                'dateFormat' => 'H:i',
                'time_24hr'  => true,
              ),
            ),
          ),
        ),

        // thursday
        array(
          'title'  => esc_html__('Thursday', 'better-chat-support'),
          'fields' => array(
            array(
              'id'       => 'availablity-thursday',
              'type'     => 'datetime',
              'from_to'  => true,
              'settings' => array(
                'noCalendar' => true,
                'enableTime' => true,
                'dateFormat' => 'H:i',
                'time_24hr'  => true,
              ),
            ),
          ),
        ),

        // friday
        array(
          'title'  => esc_html__('Friday', 'better-chat-support'),
          'fields' => array(
            array(
              'id'       => 'availablity-friday',
              'type'     => 'datetime',
              'from_to'  => true,
              'settings' => array(
                'noCalendar' => true,
                'enableTime' => true,
                'dateFormat' => 'H:i',
                'time_24hr'  => true,
              ),
            ),
          ),
        ),

        // thursday
        array(
          'title'  => esc_html__('Saturday', 'better-chat-support'),
          'fields' => array(
            array(
              'id'       => 'availablity-saturday',
              'type'     => 'datetime',
              'from_to'  => true,
              'settings' => array(
                'noCalendar' => true,
                'enableTime' => true,
                'dateFormat' => 'H:i',
                'time_24hr'  => true,
              ),
            ),
          ),
        ),

      ),
    ),

    // adding agent photo
    array(
      'id'    => 'agent-photo',
      'type'    => 'media',
      'title'   => esc_html__('Agent photo', 'better-chat-support'),
      'subtitle' => esc_html__('Add agent photo to show in the bubble.', 'better-chat-support'),
      'library' => 'image',
      'placeholder' => MCS_DIR_URL . 'assets/image/user.webp',
      'preview' => true,
      'default' => [
        'url' => MCS_DIR_URL . 'assets/image/user.webp',
      ],
    ),

    // agent name
    array(
      'id'    => 'agent-name',
      'type'    => 'text',
      'title'   => esc_html__('Agent name', 'better-chat-support'),
      'subtitle' => esc_html__('Add your/agent name for shoing in bubble.', 'better-chat-support'),
      'default' => esc_html__('John Doe', 'better-chat-support'),
    ),

    // agent subtitle
    array(
      'id'    => 'agent-subtitle',
      'type'    => 'text',
      'title'   => esc_html__('Subtitle', 'better-chat-support'),
      'subtitle' => esc_html__('Add subtitle to show under agent name', 'better-chat-support'),
      'default' => esc_html__('Typically replies within a day', 'better-chat-support'),
    ),

    // agent subtitle
    array(
      'id'    => 'agent-message',
      'type'    => 'textarea',
      'title'   => esc_html__('Message from agent', 'better-chat-support'),
      'subtitle' => esc_html__('Add add custom message for shoing in message box.', 'better-chat-support'),
      'default' => esc_html__('Hello, Welcome to the site. Please click below button for chatting me through messenger.', 'better-chat-support'),
    ),

    // before chat icon
    array(
      'id'    => 'before-chat-icon',
      'type'  => 'icon',
      'title' => esc_html__('Icon for message button', 'better-chat-support'),
      'default' => 'fab fa-facebook-messenger',
      'subtitle' => esc_html__('Change icon for adding before message button text.', 'better-chat-support'),
    ),

    // agent subtitle
    array(
      'id'    => 'chat-button-text',
      'type'    => 'text',
      'title'   => esc_html__('Message button text', 'better-chat-support'),
      'subtitle' => esc_html__('Add message button text', 'better-chat-support'),
      'default' => esc_html__('Send a message', 'better-chat-support'),
    ),

    // Autometically show popup
    array(
      'id'    => 'autoshow-popup',
      'type'    => 'switcher',
      'title'   => esc_html__('Auto open popup', 'ta-vchat'),
      'subtitle' => esc_html__('Turn ON for open popup automatically.', 'ta-vchat'),
      'default' => false,
    ),

    // Bubble position
    array(
      'id'      => 'bubble-position',
      'type'    => 'button_set',
      'title'   => esc_html__('Bubble position', 'better-chat-support'),
      'default' => 'right',
      'options'    => array(
        'right'  => esc_html__('Right', 'better-chat-support'),
        'left' => esc_html__('Left', 'better-chat-support'),
      ),
    ),
    // bubble visibility
    array(
      'id'      => 'bubble-visibility',
      'type'    => 'button_set',
      'title'   => esc_html__('Bubble visibility', 'ta-ctd'),
      'default' => 'everywhere',
      'options'    => array(
        'everywhere'  => esc_html__('Everywhere', 'ta-ctd'),
        'desktop' => esc_html__('Desktop Only', 'ta-ctd'),
        'tablet' => esc_html__('Tablet Only', 'ta-ctd'),
        'mobile' => esc_html__('Mobile Only', 'ta-ctd'),
      ),
    ),


    // Header content position
    array(
      'id'      => 'bubble-style',
      'type'    => 'button_set',
      'title'   => esc_html__('Select bubble layout mode', 'better-chat-support'),
      'default' => 'default',
      'options'    => array(
        'default'  => esc_html__('Light mode', 'better-chat-support'),
        'dark' => esc_html__('Dark mode', 'better-chat-support'),
        'night' => esc_html__('Night mode', 'better-chat-support'),
      ),
    ),

    // Header content position
    array(
      'id'      => 'header-content-position',
      'type'    => 'button_set',
      'title'   => esc_html__('Bubble header contnet position', 'better-chat-support'),
      'default' => 'center',
      'options'    => array(
        'left'  => esc_html__('Left', 'better-chat-support'),
        'center' => esc_html__('Center', 'better-chat-support'),
      ),
    ),

    // changeing bubble animations
    array(
      'id'    => 'select-animation',
      'type'  => 'select',
      'title' => esc_html__('Select animation for bubble', 'better-chat-support'),
      'options' => array(
        '1'     => esc_html__('Fade Right', 'better-chat-support'),
        '2'     => esc_html__('Fade Down', 'better-chat-support'),
        '4'     => esc_html__('Fade In Scale', 'better-chat-support'),
        '5'     => esc_html__('Rotation', 'better-chat-support'),
        '6'     => esc_html__('Slide Fall', 'better-chat-support'),
        '7'     => esc_html__('Slide Down', 'better-chat-support'),
        '3'     => esc_html__('Ease Down', 'better-chat-support'),
        '8'     => esc_html__('Rotate Left', 'better-chat-support'),
        '9'     => esc_html__('Flip Horizontal', 'better-chat-support'),
        '10'    => esc_html__('Flip Vertical', 'better-chat-support'),
        '11'    => esc_html__('Flip Up', 'better-chat-support'),
        '12'    => esc_html__('Super Scaled', 'better-chat-support'),
        '13'    => esc_html__('Slide Up', 'better-chat-support'),
        'random' => esc_html__('Random', 'better-chat-support'),
      ),
      'default'     => 'random',
    ),

    array(
      'id'      => 'opt-button-style',
      'type'    => 'image_select',
      'title'   => esc_html__('Bubble button style', 'better-chat-support'),
      'options' => array(
        '1' => MCS_DIR_URL . 'assets/image/bubble-1.png',
        '2' => MCS_DIR_URL . 'assets/image/bubble-2.png',
        '3' => MCS_DIR_URL . 'assets/image/bubble-3.png',
        '4' => MCS_DIR_URL . 'assets/image/bubble-4.png',
        '5' => MCS_DIR_URL . 'assets/image/bubble-5.png',
        '6' => MCS_DIR_URL . 'assets/image/bubble-6.png',
        '7' => MCS_DIR_URL . 'assets/image/bubble-7.png',
        '8' => MCS_DIR_URL . 'assets/image/bubble-8.png',
        '9' => MCS_DIR_URL . 'assets/image/bubble-9.png',
      ),
      'default' => '1',
    ),

    // Circle button icon
    array(
      'id'    => 'circle-button-icon',
      'type'  => 'icon',
      'title' => esc_html__('Icon for circle button', 'better-chat-support'),
      'default' => 'fab fa-facebook-messenger',
      'subtitle' => esc_html__('Change icon for circle button.', 'better-chat-support'),
    ),

    // Circle button icon close
    array(
      'id'    => 'circle-button-close',
      'type'  => 'icon',
      'title' => esc_html__('Icon for circle button close ', 'better-chat-support'),
      'default' => 'far fa-window-close',
      'subtitle' => esc_html__('Change icon for circle button close.', 'better-chat-support'),
    ),

    // changeing circle animations
    array(
      'id'    => 'circle-animation',
      'type'  => 'select',
      'title' => esc_html__('Select animation for circle icon', 'better-chat-support'),
      'options' => array(
        '1'     => esc_html__('Slide down', 'better-chat-support'),
        '2'     => esc_html__('Rotate', 'better-chat-support'),
        '3'     => esc_html__('Fade', 'better-chat-support'),
        '4'     => esc_html__('Slide Up', 'better-chat-support'),
      ),
      'default'     => '1',
    ),

    // Bubble text

    array(
      'id'    => 'bubble-text',
      'type'    => 'text',
      'title'   => esc_html__('Bubble text', 'better-chat-support'),
      'subtitle' => esc_html__('Change text to show in bubble', 'better-chat-support'),
      'default' => esc_html__('How may I help you?', 'better-chat-support'),
      'dependency' => array('opt-button-style', 'any', '2,3,4,5,6,7'),
    ),


  )
));
//
// Field: shortcodes
//
CSF::createSection($prefix, array(
  'title'       => esc_html__('SHORTCODES', 'better-chat-support'),
  'icon'        => 'fas fa-code',
  'fields'      => array(
    array(
      'id'      => 'opt-shortcode-select',
      'type'    => 'image_select',
      'title'   => esc_html__('Select button style', 'better-chat-support'),
      'options' => array(
        '1' => MCS_DIR_URL . 'assets/image/button-with-info.png',
        '2' => MCS_DIR_URL . 'assets/image/button2.png',
      ),
      'default' => '1',
    ),

    array(
      'type'    => 'content',
      'content' => '[mcs style="1" fbid="ThemeAtelier" timezone="Asia/Dhaka" photo="' . MCS_DIR_URL . 'wp-content/uploads/2022/11/user.webp" name="Jhon" designation="Techinical support" label="How can I help you?" online="I am on" offline="I am off" visibility="mSupport-show-everywhere" sizes="mSupport-btn-lg" sunday="00:00-23:59" monday="23:00-23:59" tuesday="00:00-23:59" wednesday="00:00-23:59" thursday="00:00-23:59" friday="00:00-23:59" saturday="00:00-23:59"]',
      'title' => esc_html__('Copy this shortcode and paste it in any pages/posts/widget. Edit values as you need.', 'better-chat-support'),
      'dependency' => array('opt-shortcode-select', 'any', '1'),
    ),

    array(
      'type'    => 'content',
      'content' => '[mcs style="2" fbid="ThemeAtelier" label="How can I help you?" visibility="mSupport-show-everywhere" sizes="mSupport-btn-lg"]',
      'title' => esc_html__('Copy this shortcode and paste it in any pages/posts/widget. Edit values as you need.', 'better-chat-support'),
      'dependency' => array('opt-shortcode-select', 'any', '2'),
    ),

  ),
));

//
// Field: backup
//
CSF::createSection($prefix, array(
  'title'       => esc_html__('BACKUP', 'better-chat-support'),
  'icon'        => 'fas fa-shield-alt',
  'description' => esc_html__('Export or import to use same settings in different websites.', 'better-chat-support'),
  'fields'      => array(
    array(
      'type' => 'backup',
    ),
  )
));
